[package]
name = "zkvm-openvm"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
crate-type = ["staticlib"]

[dependencies]
# `zkvm_u256_mulmod` in software (`../shims/u256_mulmod.rs`).
ruint = { version = "1.20.1", default-features = false }
ere-platform-openvm = { path = "../../crates/platform/openvm", default-features = false, features = ["getrandom-unsupported", "zkvm-accelerator"] }
openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v2.1.0-preview", default-features = false }
openvm-platform = { git = "https://github.com/openvm-org/openvm.git", tag = "v2.1.0-preview" }
openvm-riscv-guest = { git = "https://github.com/openvm-org/openvm.git", tag = "v2.1.0-preview" }

[profile.release]
codegen-units = 1
lto = "off"
panic = "abort"
