[package]
name = "ere-prover-zisk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
flate2.workspace = true
hex.workspace = true
hex-literal.workspace = true
md-5.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
reqwest = { workspace = true, features = ["rustls-tls"] }
tar.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }

# ZisK dependencies
proofman-fields.workspace = true
proofman-starks-lib-c.workspace = true
proofman-util.workspace = true
zisk-common.workspace = true
zisk-core.workspace = true
zisk-prover-backend.workspace = true
zisk-rom-setup.workspace = true
zisk-sm-rom.workspace = true
zisk-transpiler-riscv.workspace = true
ziskemu.workspace = true

# Local dependencies
ere-cluster-client-zisk.workspace = true
ere-compiler-core.workspace = true
ere-prover-core.workspace = true
ere-util-tokio.workspace = true
ere-verifier-zisk.workspace = true

[dev-dependencies]
ere-compiler-zisk.workspace = true
ere-compiler-sdk.workspace = true
ere-util-test = { workspace = true, features = ["host"] }

[features]
default = []
cuda = []

[lints]
workspace = true
